### ISSUE TITLE
code formatting errors

### ISSUE THREAD

**Issue by ChemicalSailor** [WP-API/docs#5] opened 2017-11-04 13:10 UTC
Maybe not the right repo?

I'm seeing formatting errors for special characters in the documentation due to translation of `&` to `&amp;`. Single quote ends up as `&#039;`

Tested in Safari and Chrome

**Comment by rmccue** [comment] 2017-11-05 01:28
What URLs are you seeing these on?

**Comment by ChemicalSailor** [comment] 2017-11-05 13:05
Pretty much any page in the docs with code samples - it's always the code samples.
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

**Comment by ptasker** [comment] 2017-11-06 16:19
Yep, same here: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

<img width="648" alt="screen shot 2017-11-06 at 11 18 46 am" src="https://user-images.githubusercontent.com/535651/32451230-561af0fe-c2e4-11e7-9e0b-79bc0287ef3f.png">

**Comment by rmccue** [comment] 2017-11-07 01:53
Bummer. These look correct in the [source document](https://github.com/WP-API/docs/blob/master/extending-the-rest-api/adding-custom-endpoints.md) so it seems like this may be an issue with the Jetpack Markdown integration.

**Comment by rmccue** [comment] 2017-11-07 07:45
This might be due to https://github.com/Automattic/jetpack/issues/2068 as I'm not seeing it on every page; e.g. https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/ looks fine.

**Comment by ptasker** [comment] 2017-11-30 20:46
I noticed on my own site that the issue was the SyntaxHighlighter Evolved plugin. For some reason it mangles single quotes. Is that enabled on the meta site? Disabling it and re-saving the post fixes it.

https://wordpress.org/support/topic/jp-markdown-and-code-blocks/

**Comment by terriann** [comment] 2018-01-17 21:58
I cannot reproduce the reported encoded ampersands mentioned in this issue but I added a pull request to this issue to fix a similar formatting error that was reported in Slack yesterday where the encoding was incorrect in the source document for the pagination doc page:

https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/#pagination-parameters

**Comment by rmccue** [comment] 2018-01-19 01:41
I believe this is now fixed; there was a compatibility problem with the .org plugins which has now been fixed. Thanks all!

**Closed by rmccue** 2018-01-19 01:41 UTC
